language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install pytest pytest-cov codecov
  - pip install -e .

script:
  - pytest --cov .
  - sauber --duplicates --duplicate-files --duplicate-directories --duplicate-music --duplicate-videos --duplicate-images --duplicate-documents test_data
  - sauber --find-music --find-videos --find-images --find-documents test_data

after_success:
  - codecov
